import { useState } from 'react';
import { useApp } from '../lib/store.jsx';
import { bridge } from '../lib/bridge.js';
import { useProjectGate } from '../components/common.jsx';
import logo from '../assets/ember-logo.png';

/**
 * Reports (v2): library list + white document viewer, real JSON/Markdown
 * export, regression diff. Reports are generated by the real agent.
 */
export default function Reports() {
  const { gate, project } = useProjectGate();
  const { reports, setReports, ingestReport, toast, logActivity, settings } = useApp();
  const [busy, setBusy] = useState(false);
  const [selected, setSelected] = useState(0);
  const [withProfile, setWithProfile] = useState('');
  const [aiBusy, setAiBusy] = useState(false);
  const [pdfBusy, setPdfBusy] = useState(false);

  if (gate) return gate;

  const list = reports;
  const report = list[selected] ?? list[0] ?? null;
  const profiles = Object.keys(project?.config?.testProfiles ?? {});

  const aiSummarize = async () => {
    if (!report) return;
    setAiBusy(true);
    const res = await bridge.agent.aiSummarizeReport(report, settings.aiProvider);
    setAiBusy(false);
    if (res?.ok) setReports((rs) => rs.map((r) => (r.id === report.id ? { ...r, aiExecutiveSummary: res.text, aiProvider: res.provider } : r)));
    else toast(res?.error || 'AI summary unavailable');
  };

  const generate = async () => {
    setBusy(true);
    const res = await bridge.agent.report(project.root, withProfile ? { profile: withProfile } : {});
    setBusy(false);
    if (res?.error) return toast(res.error);
    ingestReport(res);
    setSelected(0);
    toast(`Report generated — ${res.metrics.bugsFound} issue(s), crash risk ${res.metrics.crashRisk}`);
  };

  const exportAs = async (format) => {
    if (!report) return;
    const content = format === 'md' ? report.markdown ?? '' : JSON.stringify(report, null, 2);
    if (format === 'md' && !content) return toast('Markdown version unavailable for this report');
    const f = await bridge.file.saveAs({ title: `Export report (${format})`, defaultPath: `${report.id}.${format}`, content });
    if (f) {
      toast(`Exported ${f}`);
      logActivity('▤', 'var(--ok)', `Report exported (${format})`);
    }
  };

  const exportPdf = async () => {
    if (!report) return;
    setPdfBusy(true);
    const res = await bridge.agent.reportPdf(report);
    setPdfBusy(false);
    if (!res?.ok) return toast(res?.error || 'PDF export requires the Ember Desktop shell');
    const f = await bridge.file.saveAs({ title: 'Export report (PDF)', defaultPath: `${report.id}.pdf`, content: res.base64, encoding: 'base64' });
    if (f) {
      toast(`Exported ${f}`);
      logActivity('▤', 'var(--ok)', 'Report exported (pdf)');
    }
  };

  const m = report?.metrics;

  return (
    <div>
      <div style={{ display: 'flex', alignItems: 'center', gap: 16, margin: '6px 0 18px' }}>
        <h2 style={{ fontSize: 22, fontWeight: 600, margin: 0, letterSpacing: '-.02em' }}>Reports</h2>
        <div style={{ flex: 1 }} />
        <select className="input" style={{ width: 220, padding: '9px 12px' }} value={withProfile} onChange={(e) => setWithProfile(e.target.value)}>
          <option value="">signals only (scan+analyze+logs)</option>
          {profiles.map((p) => <option key={p} value={p}>include profile: {p}</option>)}
        </select>
        <button className="btn btn-white" disabled={busy} onClick={generate}>{busy ? 'Collecting signals…' : 'Generate report'}</button>
      </div>

      {report ? (
        <div style={{ display: 'grid', gridTemplateColumns: '280px 1fr', gap: 14, alignItems: 'start' }}>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 9 }}>
            {list.map((r, i) => (
              <div key={r.id} className="anim-up" onClick={() => setSelected(i)} style={{
                background: i === selected ? 'rgba(255,255,255,.05)' : 'rgba(255,255,255,.02)',
                border: `1px solid ${i === selected ? 'rgba(255,255,255,.3)' : 'rgba(255,255,255,.07)'}`,
                borderRadius: 12, padding: '14px 16px', cursor: 'pointer', transition: 'all .2s'
              }}>
                <div style={{ fontSize: 12.5, fontWeight: 500, marginBottom: 5 }}>QA Report — {r.project?.name ?? 'Project'}</div>
                <div className="micro-mono" style={{ fontSize: 10 }}>{r.id} · {new Date(r.generatedAt).toLocaleString()}</div>
                <div style={{ display: 'flex', gap: 6, marginTop: 8, flexWrap: 'wrap' }}>
                  {r.releaseReadiness && (
                    <span className={`chip ${{ ready: 'ok', 'needs-fixes': 'warn', risky: 'err' }[r.releaseReadiness.band]}`} style={{ fontSize: 8.5 }}>
                      {r.releaseReadiness.score}/100
                    </span>
                  )}
                  <span className="chip dim" style={{ fontSize: 8.5 }}>{r.metrics?.bugsFound ?? 0} issues</span>
                  {r.metrics?.severityBreakdown?.critical > 0 && <span className="chip err" style={{ fontSize: 8.5 }}>{r.metrics.severityBreakdown.critical} critical</span>}
                </div>
              </div>
            ))}
          </div>

          <div className="doc">
            <div className="doc-head">
              <img src={logo} alt="" style={{ width: 38 }} />
              <div>
                <div className="doc-title">QA Report — {report.project?.name}</div>
                <div className="doc-meta">{report.id} · {report.project?.engine} · {new Date(report.generatedAt).toLocaleString()} · {report.generator}</div>
              </div>
              <div style={{ flex: 1 }} />
              <button className="doc-btn" onClick={() => exportAs('json')}>Export JSON</button>
              <button className="doc-btn" onClick={() => exportAs('md')}>Export Markdown</button>
              <button className="doc-btn" disabled={pdfBusy} onClick={exportPdf}>{pdfBusy ? 'Rendering…' : 'Export PDF'}</button>
            </div>

            {report.releaseReadiness && (() => {
              const rr = report.releaseReadiness;
              const bandColor = { ready: '#16a34a', 'needs-fixes': '#ca8a04', risky: '#dc2626' }[rr.band];
              const bandBg = { ready: 'rgba(22,163,74,.08)', 'needs-fixes': 'rgba(202,138,4,.08)', risky: 'rgba(220,38,38,.08)' }[rr.band];
              return (
                <div style={{ display: 'flex', gap: 18, alignItems: 'center', padding: '18px 20px', borderRadius: 14, background: bandBg, border: `1px solid ${bandColor}33`, marginBottom: 24 }}>
                  <div style={{ fontSize: 34, fontWeight: 700, fontFamily: 'var(--font-mono)', color: bandColor, lineHeight: 1 }}>{rr.score}<span style={{ fontSize: 15, opacity: .5 }}>/100</span></div>
                  <div style={{ flex: 1 }}>
                    <div style={{ fontSize: 14, fontWeight: 700, color: bandColor }}>{rr.bandLabel.toUpperCase()}</div>
                    <div style={{ fontSize: 11, color: 'rgba(24,24,27,.55)', marginTop: 2 }}>Release Readiness — {rr.note}</div>
                    {rr.blocksRelease.length > 0 && (
                      <div style={{ marginTop: 8, fontSize: 11.5, color: 'rgba(24,24,27,.75)' }}>
                        <b>What blocks release:</b> {rr.blocksRelease.join(' ')}
                      </div>
                    )}
                    {rr.risksIfShipped.length > 0 && (
                      <div style={{ marginTop: 4, fontSize: 11.5, color: 'rgba(24,24,27,.75)' }}>
                        <b>Risks if you ship today:</b> {rr.risksIfShipped.join(' ')}
                      </div>
                    )}
                  </div>
                </div>
              );
            })()}

            <div className="doc-sec">Executive summary</div>
            <p style={{ margin: '0 0 24px' }}>{report.executiveSummary}</p>

            <div className="doc-sec">AI summary{report.aiProvider ? ` (${report.aiProvider === 'openai' ? 'OpenAI' : 'Claude Fable 5'})` : ''}</div>
            {report.aiExecutiveSummary ? (
              <p style={{ margin: '0 0 24px' }}>{report.aiExecutiveSummary}</p>
            ) : (
              <p style={{ margin: '0 0 24px' }}>
                <button className="doc-btn" disabled={aiBusy} onClick={aiSummarize}>{aiBusy ? 'Asking AI…' : 'Generate AI summary'}</button>
              </p>
            )}

            {m && (
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4,1fr)', gap: 10, marginBottom: 26 }}>
                {[
                  ['Files scanned', m.filesScanned], ['Logs analyzed', m.logsAnalyzed],
                  ['Bugs found', m.bugsFound], ['Crash risk', m.crashRisk],
                  ['Failed checks', m.failedChecks], ['Blocked checks', m.blockedChecks ?? 0],
                  ['Regression risk', m.regressionRisk], ['Build health', m.buildHealth]
                ].map(([label, value]) => (
                  <div key={label} className="doc-stat">
                    <div style={{ fontSize: 20, fontWeight: 600, fontFamily: 'var(--font-mono)', color: '#18181b' }}>{String(value)}</div>
                    <div style={{ fontSize: 9.5, color: 'rgba(24,24,27,.5)', marginTop: 2 }}>{label}</div>
                  </div>
                ))}
              </div>
            )}

            {report.regression && (
              <>
                <div className="doc-sec">Regression vs {report.regression.comparedTo}</div>
                <p style={{ margin: '0 0 24px', fontSize: 12 }}>
                  <b style={{ color: '#16a34a' }}>{report.regression.fixed.length} fixed</b> · {report.regression.stillPresent} still present ·{' '}
                  <b style={{ color: '#dc2626' }}>{report.regression.new.length} new</b>
                  {report.regression.fixed.length > 0 && <> — fixed: {report.regression.fixed.slice(0, 3).join('; ')}</>}
                </p>
              </>
            )}

            <div className="doc-sec">Top findings</div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 8, marginBottom: 26 }}>
              {(report.bugs ?? []).slice(0, 6).map((b) => (
                <div key={b.id} style={{ display: 'flex', gap: 10, fontSize: 12, lineHeight: 1.55, color: 'rgba(24,24,27,.8)' }}>
                  <span style={{
                    fontWeight: 600, flex: 'none', fontFamily: 'var(--font-mono)', fontSize: 10, marginTop: 2,
                    color: { critical: '#dc2626', high: '#ea580c', medium: '#ca8a04', low: '#2563eb' }[b.severity]
                  }}>
                    {b.severity.slice(0, 4).toUpperCase()}
                  </span>
                  {b.title}{b.filesInvolved?.[0] ? ` (${b.filesInvolved[0]}${b.line ? `:${b.line}` : ''})` : ''}
                </div>
              ))}
              {(report.bugs ?? []).length === 0 && <div style={{ fontSize: 12, color: 'rgba(24,24,27,.5)' }}>No issues opened from the available signals.</div>}
            </div>

            {report.blockers?.length > 0 && (
              <>
                <div className="doc-sec">Blocked (what Ember could not do yet)</div>
                <div style={{ display: 'flex', flexDirection: 'column', gap: 6, marginBottom: 26 }}>
                  {report.blockers.slice(0, 5).map((b, i) => (
                    <div key={i} style={{ fontSize: 11.5, lineHeight: 1.55, color: 'rgba(24,24,27,.6)', fontFamily: 'var(--font-mono)' }}>⚠ {b.message}</div>
                  ))}
                </div>
              </>
            )}

            <div className="doc-sec">Recommended next actions</div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
              {(report.recommendedNextActions ?? []).map((a) => (
                <div key={a} style={{ fontSize: 12, lineHeight: 1.55, color: 'rgba(24,24,27,.8)' }}>→ {a}</div>
              ))}
            </div>
          </div>
        </div>
      ) : (
        <div className="empty-hero">
          <div className="e-title">No reports generated yet</div>
          <div className="e-sub">Generate one — Ember collects fresh signals (scan, static analysis, log mining, optional test profile), builds the QA report and diffs it against the previous one.</div>
          <button className="btn btn-white" onClick={generate} disabled={busy}>{busy ? 'Collecting signals…' : 'Generate first report'}</button>
        </div>
      )}
    </div>
  );
}
